"""Extract summary metadata from study datasets.

Thin wrapper over bids_studies extraction functions. Reads from
hierarchical TSV files (sourcedata.tsv) generated by extract_study_stats()
and aggregates to study level via aggregate_to_study().

Phase 1 (raw metadata) is always extracted directly from dataset_description.json.
"""

import logging
from pathlib import Path
from typing import Any

from bids_studies.extraction.raw_metadata import extract_raw_metadata
from bids_studies.extraction.study import aggregate_to_study
from bids_studies.extraction.tsv import read_datasets_tsv

logger = logging.getLogger(__name__)

# Extraction version - increment when extraction logic changes
# Format: MAJOR.MINOR.PATCH (semantic versioning)
# - MAJOR: Breaking schema changes
# - MINOR: New metrics added (backward compatible)
# - PATCH: Bug fixes, no schema changes
EXTRACTION_VERSION = "1.2.0"  # Consolidate extraction: use bids_studies for all phases


def extract_all_summaries(
    study_path: Path,
    stage: str = "basic",
) -> dict[str, Any]:
    """Extract all summary metadata for a study.

    Reads from hierarchical TSV files produced by bids_studies.extraction.
    The sourcedata/sourcedata.tsv file must exist (generated by
    extract_study_stats() before this function is called).

    Args:
        study_path: Path to study directory
        stage: Extraction stage
            - "basic": Only raw metadata (author, version)
            - "counts", "sizes", "imaging": + aggregated stats from sourcedata.tsv

    Returns:
        Dictionary with all extracted metadata
    """
    result: dict[str, Any] = {}

    # Phase 1: Raw metadata (always)
    result.update(extract_raw_metadata(study_path))

    if stage in ("counts", "sizes", "imaging"):
        sourcedata_tsv = study_path / "sourcedata" / "sourcedata.tsv"
        if sourcedata_tsv.exists():
            logger.debug(f"Reading from hierarchical TSV: {sourcedata_tsv}")
            datasets_stats = read_datasets_tsv(sourcedata_tsv)
            study_stats = aggregate_to_study(datasets_stats)

            # Map bids_studies field names to studies.tsv column names
            if "bold_voxels_total" in study_stats:
                study_stats["bold_voxels"] = study_stats.pop("bold_voxels_total")
            # bold_voxels_mean and bold_duration_mean are extra — caller ignores them

            result.update(study_stats)
        else:
            logger.warning(
                f"Hierarchical TSV not found at {sourcedata_tsv}. "
                f"Run extract_study_stats() first."
            )

    return result
